updateDocsComment: >
  Thanks for the pull request! TShock's maintainers would like you to go ahead and give yourself credit by updating the `CHANGELOG.md` as soon as you can. Your pull request will likely not be accepted without this. This both helps us document changes to TShock, as well as give you credit for your work. You deserve it, so go take credit! :sparkles: Please note: if you do not update the changelog, your pull request may sit ignored for many days, months, or years. If you do not fix this, you should not expect your changes to be merged. Please see our helpful video tutorial on how to do this: https://youtu.be/GzEjcYj-LGA.

updateDocsWhiteList:
  - bug
  - chore

updateDocsTargetFiles:
  - README
  - CHANGELOG.md
