name: MSBuild Test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.5.1'
    - run: dotnet build --configuration Release ./TShockAPI/TShockAPI.csproj
