name: Build + Deploy
on: 
  release:
    types: [prereleased]
    branches: [prospect] #限制只有前瞻版
    
jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

       - name: Run tests
        run: dotnet test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["win-x64", "osx-x64", "linux-x64", "linux-arm64", "linux-arm"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

      - name: Install msgfmt
        run: sudo apt-get install -y gettext

      - name: 编译安装程序
        run: |
            cd TShockInstaller
            dotnet publish -r ${{ matrix.arch }} -f net6.0 -c Release -p:PublishSingleFile=true --self-contained true
      - name: 主体构建
        run: |
            cd TShockLauncher
            dotnet publish -r ${{ matrix.arch }} -f net6.0 -c Release -p:PublishSingleFile=true --self-contained false
            
      - name: 增加权限
        if: ${{ matrix.arch != 'win-x64' }}
        run: |
            chmod +x TShockLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/TShock.Server
      - name: 复制启动程序
        run: |
            cp TShockInstaller/bin/Release/net6.0/${{ matrix.arch }}/publish/* TShockLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/
            
      # preserve file perms: https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: 压缩非windows (non-Windows)
        if: ${{ matrix.arch != 'win-x64' }}
        run: |
            cd TShockLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/
            tar -cvf ../../../../../../TShock-前瞻-${{ matrix.arch }}-Release.tar *
            
            
      #- name: 上传非windos版 (non-Windows)
        #uses: actions/upload-artifact@v3
        #if: ${{ matrix.arch != 'win-x64' }}
        #with:
          #name: TShock-Beta-${{ matrix.arch }}-Release
          #path: TShock-Beta-${{ matrix.arch }}-Release.tar
          
       - name: 上传非windos版 (non-Windows)
       uses: svenstaro/upload-release-action@v2
       if: ${{ matrix.arch != 'win-x64' }}
       with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: TShock-前瞻-${{ matrix.arch }}-Release.tar
        overwrite: true
          
          

      #- name: 上传windows版 (Windows)
        #uses: actions/upload-artifact@v3
        #if: ${{ matrix.arch == 'win-x64' }}
        #with:
          #name: TShock-Beta-${{ matrix.arch }}-Release
          #path: TShockLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/
          
        - name: 压缩windows
        if: ${{ matrix.arch == 'win-x64' }}
        run: |
            cd TShockLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/
            zip ../../../../../../TShock-前瞻-${{ matrix.arch }}-Release.zip *
          
    - name: 上传windows版 (Windows)
       uses: svenstaro/upload-release-action@v2
       if: ${{ matrix.arch == 'win-x64' }}
       with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: TShock-前瞻-${{ matrix.arch }}-Release.zip
        overwrite: true
        
  deploy:
    name: 加备注
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
          
      - name: 修改预发布的备注
       uses: irongut/EditRelease@v1.2.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         id: ${{ github.event.release.id }}
         body: "⚠Please pay attention to backup. The forward-looking version may cause your data loss.\n++++"
